// Isolated preview checks. API requests are blocked; no real users or messages.
import { chromium } from '../../backend/build/chat-ui/node_modules/playwright/index.mjs'
import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'
const root = process.env.UI_CHECK_URL || 'http://127.0.0.1:15179'
assert.ok(/^http:\/\/127\.0\.0\.1:\d+$/.test(root))
const output = 'backend/build/chat-ui/workspace'
await mkdir(output, { recursive: true })
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true })
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' })
const page = await context.newPage(), errors = [], apiRequests = [], passed = []
context.on('page', tab => tab.on('pageerror', error => errors.push(error.message)))
page.on('pageerror', error => { errors.push(error.message); console.error(error.stack) })
await context.route('**/api/**', route => { if (!new URL(route.request().url()).pathname.startsWith('/api/')) return route.continue(); apiRequests.push(route.request().url()); return route.abort() })
async function openComposer(kind) {
  await page.getByRole('button', { name: '＋ 새 글 작성', exact: true }).click()
  const modal = page.locator('dialog[open]')
  await modal.getByLabel('작성 종류').selectOption({ label: kind })
  return modal
}
try {
  await page.goto(root + '/planner/daily')
  const mode = page.getByRole('navigation', { name: '플래너 보기' })
  await mode.waitFor()
  assert.equal(await mode.getByRole('link').count(),4)
  await mode.getByRole('link', { name:'주간', exact:true }).click()
  await page.waitForURL('**/planner/weekly?*')
  assert.equal(await mode.getByRole('link',{name:'주간',exact:true}).getAttribute('aria-current'),'page')
  await page.getByRole('button',{name:'이 보기를 기본으로',exact:true}).click()
  assert.equal(await page.evaluate(()=>localStorage.getItem('timebar.planner.default-view')),'weekly')
  passed.push('planner four modes and persisted default')

  let modal = await openComposer('할 일')
  const initialBox = await modal.boundingBox()
  await modal.getByLabel('제목', { exact:true }).fill('브라우저 검증 할 일')
  await modal.getByLabel('새 체크리스트 항목').fill('초안 검토')
  await modal.getByRole('button',{name:'추가',exact:true}).click()
  await modal.getByLabel('초안 검토 담당자').selectOption('self')
  await modal.getByLabel('초안 검토 완료').check()
  await modal.getByRole('button',{name:'할 일 저장',exact:true}).click()
  await page.waitForURL('**/tasks')
  const storedTask = await page.evaluate(()=>JSON.parse(localStorage.getItem('timeflow.demo.v1.tasks')).find(item=>item.title==='브라우저 검증 할 일'))
  assert.equal(storedTask.subtasks[0].assigneeId,'self')
  assert.equal(storedTask.subtasks[0].done,true)
  await page.getByRole('button',{name:'상세 보기',exact:true}).click()
  await page.getByLabel('초안 검토 담당자').selectOption('1')
  await page.getByRole('button',{name:'저장하기',exact:true}).click()
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('timeflow.demo.v1.tasks')).find(item=>item.title==='브라우저 검증 할 일').subtasks[0].assigneeId),'1')
  passed.push('checklist completion and per-item assignee survive creation and editing')

  modal = await openComposer('일정')
  await modal.getByLabel('제목',{exact:true}).fill('브라우저 검증 반복 일정')
  await modal.getByLabel('반복 주기',{exact:true}).selectOption('weekly')
  await modal.getByRole('button',{name:'월요일',exact:true}).click()
  await modal.getByLabel('반복 종료',{exact:true}).selectOption('count')
  await modal.getByLabel('반복 횟수').fill('3')
  await modal.getByRole('button',{name:'일정 저장',exact:true}).click()
  await page.waitForURL('**/events')
  const storedEvent = await page.evaluate(()=>JSON.parse(localStorage.getItem('timeflow.demo.v1.events')).find(item=>item.title==='브라우저 검증 반복 일정'))
  assert.equal(storedEvent.recurrence.count,3)
  assert.ok(storedEvent.recurrence.weekdays.includes(1))
  passed.push('event recurrence controls persist rules')

  modal = await openComposer('할 일')
  for (const kind of ['일정','루틴','업무 기록','업무 위키','할 일']) {
    await modal.getByLabel('작성 종류').selectOption({label:kind})
    const box = await modal.boundingBox()
    assert.equal(box.width,initialBox.width)
    assert.equal(box.height,initialBox.height)
    assert.equal(await modal.locator('.modal-body button[type="submit"]').count(),0)
    assert.ok(await modal.locator('.modal-footer button[type="submit"]').isVisible())
  }
  await page.screenshot({path:output+'/composer-desktop.png'})
  for (const width of [390,320]) {
    await page.setViewportSize({width,height:568})
    await modal.getByLabel('작성 종류').selectOption('루틴')
    const box = await modal.boundingBox(), footer = await modal.locator('.modal-footer').boundingBox()
    assert.ok(box.x>=0 && box.x+box.width<=width)
    assert.ok(footer.y+footer.height<=568)
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))
    await page.screenshot({path:output+`/composer-${width}.png`})
  }
  await modal.getByRole('button',{name:'취소',exact:true}).click()
  passed.push('all compose types keep fixed modal size and pinned actions at 320px')

  await page.setViewportSize({width:1440,height:1000})
  await page.goto(root+'/chat')
  const panel = page.locator('.floating-chat')
  await panel.locator('.chat-room-item').filter({hasText:'목요일 회고 모임'}).click()
  const input = panel.getByRole('textbox',{name:'메시지',exact:true})
  await input.fill('안녕 @')
  await panel.getByRole('listbox',{name:'멘션할 참여자'}).getByRole('option',{name:'@서연',exact:true}).click()
  assert.equal(await input.inputValue(),'안녕 @서연 ')
  await panel.getByRole('button',{name:'메시지 보내기',exact:true}).click()
  await panel.getByRole('log').getByText('안녕 @서연',{exact:true}).waitFor()
  await input.fill('@민')
  await input.press('Enter')
  assert.equal(await input.inputValue(),'@민준 ')
  await input.fill('')
  passed.push('typing @ opens filtered member suggestions; pointer and Enter select without sending')

  await panel.getByRole('button',{name:'메시지 검색',exact:true}).click()
  await panel.locator('.chat-message-search input').fill('추천')
  await panel.getByRole('log').getByText('@지수 저도 다음 주부터 함께하고 싶어요. 추천하는 책이 있나요? #독서',{exact:true}).waitFor()
  assert.equal(await panel.locator('.chat-message').count(),1)
  await panel.locator('.chat-message-search input').fill('')
  await panel.getByRole('button',{name:'통합 검색',exact:true}).click()
  await page.locator('dialog .unified-search-input input').fill('수고')
  await page.locator('dialog .unified-search-hit').filter({hasText:'이번 주도 수고'}).click()
  await panel.locator('.chat-search-match').waitFor()
  await panel.getByRole('button',{name:'최근 대화로',exact:true}).click()
  passed.push('room history and integrated search open matched messages')
  for(const width of [390,320]) {
    await page.setViewportSize({width,height:568})
    const button=await panel.getByRole('button',{name:'메시지 보내기',exact:true}).boundingBox()
    assert.ok(button.y+button.height<=568)
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))
    await page.screenshot({path:output+`/messenger-${width}.png`})
  }
  passed.push('320px messenger remains usable without horizontal overflow')

  await page.setViewportSize({width:1440,height:1000})
  await panel.getByRole('button',{name:'채팅 최소화',exact:true}).click()
  await page.goto(root+'/events')
  await page.locator('.manage .row').first().click()
  await page.locator('dialog .edit-presence').waitFor()
  const second=await context.newPage()
  await second.goto(root+'/events')
  await second.locator('.manage .row').first().click()
  await page.locator('dialog .edit-presence').getByText(/다른 창에서 수정 중/).waitFor()
  await second.locator('dialog').getByRole('button',{name:'취소',exact:true}).click()
  await page.waitForFunction(()=>!document.querySelector('dialog .edit-presence')?.textContent.includes('다른 창'))
  await second.close()
  passed.push('same-browser edit presence identifies competing editor and clears on close')
  await page.locator('dialog').getByRole('button',{name:'취소',exact:true}).click()

  const launcher=page.locator('.floating-chat-launcher'), box=await launcher.boundingBox()
  await page.mouse.move(box.x+28,box.y+28); await page.mouse.down(); await page.mouse.move(140,180,{steps:8}); await page.mouse.up()
  const position=await launcher.boundingBox()
  await page.reload()
  const restored=await launcher.boundingBox()
  assert.ok(Math.abs(position.x-restored.x)<1 && Math.abs(position.y-restored.y)<1)
  passed.push('movable launcher persists position across reload')
  assert.deepEqual(errors,[])
  assert.deepEqual(apiRequests,[])
  await writeFile(output+'/results.json',JSON.stringify({passed,pageErrors:errors,apiRequests:apiRequests.length},null,2))
  console.log(JSON.stringify({passed:passed.length,pageErrors:errors.length,apiRequests:apiRequests.length}))
} catch(error) { console.error(JSON.stringify({pageErrors:errors,passed})); await page.screenshot({path:output+'/failure.png'}); throw error }
finally { await browser.close() }
